FROM nginx:stable-alpine

###############################################################################
#                                INSTALLATION
###############################################################################

### install Filebeat

ENV FILEBEAT_VERSION 6.3.0


RUN apt-get update -qq \
 && apt-get install -qqy curl \
 && apt-get clean

RUN curl -L -O https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-${FILEBEAT_VERSION}-amd64.deb \
 && dpkg -i filebeat-${FILEBEAT_VERSION}-amd64.deb \
 && rm filebeat-${FILEBEAT_VERSION}-amd64.deb

# config file
ADD filebeat.yml /etc/filebeat/filebeat.yml
RUN chmod 644 /etc/filebeat/filebeat.yml

###############################################################################

# install wget and unzip
RUN apk update && apk add bash openssl && rm -rf /var/cache/apk/*

RUN mkdir -p /etc/nginx/ssl/ \
    && openssl req \
            -x509 \
            -subj "/C=AU/ST=HELLO/L=MYPLACE/O=ALONGWAY" \
            -nodes \
            -days 365 \
            -newkey rsa:2048 \
            -keyout /etc/nginx/ssl/certificate.key \
            -out /etc/nginx/ssl/certificate.crt

COPY ./nginx.conf /etc/nginx/nginx.conf
COPY ./default.conf /etc/nginx/conf.d/default.conf
#
#COPY ../certificate.crt:/etc/nginx/ssl/certificate.crt
#COPY ../certificate.key:/etc/nginx/ssl/certificate.key
#COPY ../app.htpasswd:/etc/nginx/conf.d/app.htpasswd
#COPY ../kibana.htpasswd:/etc/nginx/conf.d/kibana.htpasswd

# remove log symlinks
#RUN rm /var/log/nginx/access.log /var/log/nginx/error.log
RUN unlink /var/log/nginx/access.log
RUN unlink /var/log/nginx/error.log

