version: '2.0'
services:
  elasticsearch1:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.1.3
    container_name: elasticsearch1
    environment:
      - node.name=country01
      - cluster.name=country
      - bootstrap.memory_lock=true
      - node.master=true
      - node.ingest=false
      - "ES_JAVA_OPTS=-Xms612m -Xmx612m"
    ports:
      - 9200:9200
    ulimits:
      memlock:
        soft: -1
        hard: -1
      mem_limit: 900m
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    networks:
      - esnet
volumes:
  esdata1:
    driver: local
networks:
  esnet:
