version: '2.0'
services:
  country-api:
    restart: always
    build: ./my-api
    command: gunicorn --workers=2 -b :8080 python-app:app 
    networks:
      - country

  country-nginx:
    build: ./my-nginx
    environment:
      CERTBOT_EMAIL: "john@swarmee.net"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - country-nginx-data:/var/log/nginx
    networks:
      - country

networks:
  country:

volumes:
  country-nginx-data:
    driver: local  
