version: '2'

services:

  suburb-api:
    container_name: suburb-api1
    restart: always
    build: ./suburb-api
    mem_limit: 1000m 
    command: gunicorn -w 1 -b :8000 suburb-api:app 
    networks:
      - esnet

  nginx:
    container_name: nginx
    restart: always
    build: ./nginx
    mem_limit: 500m
    ports:
      - "80:80"
    depends_on:
      - suburb-api
    networks:
      - esnet

networks:
  esnet:
