##
##  https://github.com/robbert229/docker-elk-nginx
###
version: '2.1'
services:
  python-api:
    container_name: python-api1
    restart: always
    build: ./python-api
    mem_limit: 1000m  
    command: gunicorn --workers=1 -b :8080 python-api:app 
    networks:
      - apinet

  nginx1:
    image: nginx:stable-alpine
    container_name: nginx1
    mem_limit: 400m 
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./certificate.crt:/etc/nginx/ssl/certificate.crt
      - ./certificate.key:/etc/nginx/ssl/certificate.key
      - ./app.htpasswd:/etc/nginx/conf.d/app.htpasswd
      - ./default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - apinet
    depends_on: 
      - python-api

networks:
  apinet:
