version: '2.1'
services:
  elasticsearch1:
    build: ./my-elasticsearch
    container_name: elasticsearch1
    ports:
      - 9200:9200
    mem_limit: 600m
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    healthcheck:
      test: ["CMD", "curl","-s" ,"-f", "http://localhost:9200/_cat/health"]
    networks:
      - esnet
    restart: on-failure

#  geonames-cities-api:
#    container_name: geonames-cities-api1
#    restart: always
#    build: ./geonames-cities-api
#    mem_limit: 200m  
#    command: gunicorn --workers=1 -b :8080 geonames-cities-api:app 
#    networks:
#      - esnet
#    depends_on:
#      elasticsearch1:  { condition: service_healthy }

#  nginx1:
#    image: nginx:stable-alpine
#    container_name: nginx1
#    mem_limit: 200m 
#    ports:
#      - 80:80
#      - 443:443
#    volumes:
#      - ./nginx:/var/log/nginx/
#      - ./default.conf:/etc/nginx/conf.d/default.conf
#    networks:
#      - esnet
#    depends_on:
#      elasticsearch1:  { condition: service_healthy }

volumes:
  esdata1:
    driver: local
#  fbdata:
#    driver: local

networks:
  esnet: