version: '2.1'
services:
  logstash-icij:
    build: ./my-logstash-icij
    environment:
      ELASTICSEARCH_HOST: elasticsearch
      ELASTICSEARCH_PORT: 9200
      HEAP_SIZE: 300m
    mem_limit: 900m  
    networks:
      - esnet

networks:
  esnet:
