##
##  https://github.com/robbert229/docker-elk-nginx
###
version: '2.0'
services:
  elasticsearch1:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.2.3
    container_name: elasticsearch1
    environment:
      - node.name=swarmee01
      - cluster.name=swarmee
      - bootstrap.memory_lock=true
      - node.master=true
        #      - xpack.security.enabled=false 
      - "ES_JAVA_OPTS=-Xms200m -Xmx200m"
    ports:
      - 9200:9200
    ulimits:
      memlock:
        soft: -1
        hard: -1
      mem_limit: 450m
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    networks:
      - esnet

  productsearch-api:
    container_name: productsearch-api1
    restart: always
    build: ./productsearch-api
    mem_limit: 200m 
    command: gunicorn -w 1 -b :8080 productsearch-api:app 
    networks:
      - esnet

  nginx1:
    image: nginx:stable-alpine
    container_name: nginx1
    ulimits:
      mem_limit: 200m
    ports:
      - 80:80
    volumes:
      - ./certificate.crt:/etc/nginx/ssl/certificate.crt
      - ./certificate.key:/etc/nginx/ssl/certificate.key
      - ./app.htpasswd:/etc/nginx/conf.d/app.htpasswd
      - ./default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - esnet
    depends_on:
      - elasticsearch1

  filebeat1:
    image: docker.elastic.co/beats/filebeat:6.2.3
    container_name: filebeat1
    mem_limit: 100m
    ports:
      - 81:80
    networks:
      - esnet
    depends_on:
      - elasticsearch1


volumes:
  esdata1:
    driver: local

networks:
  esnet:
