version: '2.1'
services:
  logstash:
    build: ./my-logstash
    container_name: logstash-cities-api
    environment:
      ELASTICSEARCH_HOST: elasticsearch
      ELASTICSEARCH_PORT: 9200
      HEAP_SIZE: 300m
    networks:
      - esnet
    volumes:
      - addressdata:/tmp/geonames/

  python-app:
    restart: always
    build: ./python-app
    mem_limit: 200m  
    command: gunicorn --workers=1 -b :8080 python-app:app 
    networks:
      - esnet

  elasticsearch:
    build: ./my-elasticsearch
#    container_name: elasticsearch - if you name containers you can't scale them
    mem_limit: 500m
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    networks:
      - esnet
 
  kibana:
    image: docker.elastic.co/kibana/kibana-oss:6.2.4
    environment:
      SERVER_NAME: swarmee
      VEGA_ENABLEEXTERNALURLS: "true" 
      ELASTICSEARCH_URL: http://elasticsearch:9200
    mem_limit: 400m
    networks:
      - esnet
    restart: always

  nginx:
    build: ./my-nginx
    mem_limit: 200m 
    ports:
      - 80:80
      - 9200:9200
      - 5601:5601      
    volumes:
      - ./logs/nginx:/var/log/nginx/
      - ./security/certificate.crt:/etc/nginx/ssl/certificate.crt
      - ./security/certificate.key:/etc/nginx/ssl/certificate.key
      - ./security/app.htpasswd:/etc/nginx/conf.d/app.htpasswd
      - ./security/kibana.htpasswd:/etc/nginx/conf.d/kibana.htpasswd
    networks:
      - esnet

  download_data:
    container_name: download_data
    build: ./my-data-dowloader
    mem_limit: 200m
    networks: 
      - esnet
    depends_on: 
      - elasticsearch
    volumes:
      - addressdata:/tmp/geonames/

  filebeat:
    build: ./my-filebeat
    command: ./filebeat -e --modules=nginx --setup 
    mem_limit: 100m
    volumes:
      - ./logs/nginx:/var/log/nginx/
      - fbdata:/usr/share/filebeat/data/
    networks:
      - esnet
    restart: on-failure
  


volumes:
  esdata1:
    driver: local
  addressdata:
    driver: local
  fbdata:
    driver: local    

networks:
  esnet:
