##
##  https://github.com/robbert229/docker-elk-nginx
###
version: '2.0'
services:
  elasticsearch:
#    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.2.3
#    image: docker.elastic.co/elasticsearch/elasticsearch:6.3.0
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.3.0
    environment:
      - node.name=swarmee01
      - cluster.name=swarmee
      - bootstrap.memory_lock=true
      - node.master=true
#      - xpack.security.enabled=false 
      - "ES_JAVA_OPTS=-Xms500m -Xmx500m"
    ports:
      - 9200:9200
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 800m
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    networks:
      - esnet

        #  nginx1:
        #    image: nginx:stable-alpine
        #    container_name: nginx1
        #    ulimits:
        #      mem_limit: 400m
        #    ports:
        #      - 444:444
        #      - 443:443
        #    volumes:
        #      - ./certificate.crt:/etc/nginx/ssl/certificate.crt
        #      - ./certificate.key:/etc/nginx/ssl/certificate.key
        #      - ./kibana.htpasswd:/etc/nginx/conf.d/kibana.htpasswd
        #      - ./default.conf:/etc/nginx/conf.d/default.conf
        #    networks:
        #      - esnet
        #    depends_on:
        #      - elasticsearch1

  kibana:
#    image: docker.elastic.co/kibana/kibana-oss:6.2.3
#    image:  docker.elastic.co/kibana/kibana:6.3.0
    image:  docker.elastic.co/kibana/kibana-oss:6.3.0
    environment:
      SERVER_NAME: swarmee
      VEGA_ENABLEEXTERNALURLS: "true" 
      ELASTICSEARCH_URL: http://elasticsearch:9200
#      XPACK_SECURITY_ENABLED: "false" 
#      KIBANA_DEFAULTAPPID: "dashboard/4c1cb360-2a5b-11e8-bfcf-fd22dc5fb3d6"
    mem_limit: 500m
    ports:
      - 5601:5601
    networks:
      - esnet
    depends_on:
      - elasticsearch

  configure_stack:
    container_name: load-sample-data
    build: ./load-sample-data
    mem_limit: 200m  
#volumes: ['./my-alpine/configure-stack.sh:/usr/local/bin/configure-stack.sh:ro']
    command: ['/bin/bash', '-c', 'cat /tmp/sample/load-sample-data.sh | tr -d "\r" | bash']
    networks: 
      - esnet
    depends_on: 
      - elasticsearch

volumes:
  esdata1:
    driver: local

networks:
  esnet:
