##
##  https://github.com/robbert229/docker-elk-nginx
###
version: '2.0'
services:
  elasticsearch:
    build: ./my-elasticsearch
    environment:
      - node.name=swarmee01
      - cluster.name=swarmee
      - bootstrap.memory_lock=true
      - node.master=true
    ports:
      - 9200:9200
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 450m
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    networks:
      - esnet

  productsearch-api:
    restart: always
    build: ./productsearch-api
    mem_limit: 200m 
    command: gunicorn -w 1 -b :8080 productsearch-api:app 
    networks:
      - esnet

  nginx:
    build: ./my-nginx
    mem_limit: 200m 
    ports:
      - 443:443  
      - 80:80    
#    volumes:
#      - ./security/app.htpasswd:/etc/nginx/conf.d/app.htpasswd
#      - ./security/kibana.htpasswd:/etc/nginx/conf.d/kibana.htpasswd
    networks:
      - esnet
    depends_on: 
      - elasticsearch

  logstash:
    build: ./my-logstash
    environment:
      ELASTICSEARCH_HOST: elasticsearch
      ELASTICSEARCH_PORT: 9200
      HEAP_SIZE: 500m
    networks:
      - esnet

volumes:
  esdata1:
    driver: local

networks:
  esnet:
