version: '2.0'
services:
  logstash:
    build: ./my-logstash
    container_name: logstash1
    environment:
      ELASTICSEARCH_HOST: swarmee.net
      ELASTICSEARCH_PORT: 9200
      HEAP_SIZE: 500m
    volumes:
      - ./pipeline/:/usr/share/logstash/pipeline:rw
      - ./data/:/tmp:rw
    ports:
             - "5000:5000"
             - "5001:5001"
    networks:
      - esnet

networks:
  esnet:
